config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :jobs
  resources :clients
  resources :base_slas
  resources :users, only: [:index, :show]

end

app/models/base_sla.rb
class BaseSla < ActiveRecord::Base
  validates_presence_of :quantity, :period, :name

  validates :period, inclusion: ['hours', 'days', 'hour', 'day']
  has_many :client_slas
end

app/models/business_unit.rb
class BusinessUnit < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base

validates_presence_of :name, :wfm_id


has_many :jobs
has_many :client_slas

end

app/models/client_sla.rb
class ClientSla < ActiveRecord::Base

 belongs_to :base_slas
end

app/models/job.rb
class Job < ActiveRecord::Base

  validates_presence_of :job_no, :job_type, :job_state, :start_date, :due_date, :client_id

  belongs_to :client
  has_many :job_slas
end

app/models/job_sla.rb
class JobSla < ActiveRecord::Base
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
   validates_presence_of :name, :value, :lookup_type
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates_presence_of :user_role
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         #:registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  validates_presence_of :first_name, :last_name, :email, :mobile, :role_id


  validates_format_of :email,
    :with  => Devise.email_regexp,
    :allow_blank => true,
    :if => :email_changed?


  belongs_to :role
end

app/models/wfm_call.rb
class WfmCall < ActiveRecord::Base
  after_initialize :default_values

  def default_values
    @api_user = ENV["WFM_API_USER"]
    @api_key = ENV["WFM_API_KEY"]
    @base_uri = 'https://api.workflowmax.com/job.api/'

  end

  def build_request
    #Need to Build the base get request
    @uri = "#{@base_uri}#{@module}?apiKey=#{@api_key}&accountKey=#{@api_user}"
  end

  def request
    rest_data = RestClient.get(@uri)
    return rest_data
  end

  def clientvalidate(id, name)
    clientcheck = Client.find_by_wfm_id(id)
    if clientcheck == nil
      Client.create(name: name, wfm_id: id)
      puts "Client Created #{name}"
      clientcheck = Client.find_by_wfm_id(id)
    end

    if clientcheck.name != name
      Client.update(clientcheck.id, name: name)
      puts "Client Name changed"
    end

    return clientcheck.id

  end

  def jobvalidate(id, job_type, job_state, start_date, due_date, client_id)
    jobcheck = Job.find_by_job_no(id)
    if jobcheck == nil
      Job.create(job_no: id, job_type: job_type, job_state: job_state, start_date: start_date, due_date: due_date, client_id: client_id)
      puts "Job Created #{job_type}"
      jobcheck = Job.find_by_job_no(id)
    end

    if jobcheck.job_type != job_type
      Job.update(jobcheck.id, job_type: job_type)
      puts "Job Name changed"
    end

    if jobcheck.job_state != job_state
      Job.update(jobcheck.id, job_state: job_state)
      puts "Job State changed"
    end

    if jobcheck.start_date != start_date
      Job.update(jobcheck.id, start_date: start_date)
      puts "Job Start changed"
    end

    if jobcheck.due_date != due_date
      Job.update(jobcheck.id, due_date: due_date)
      puts "Job Due changed"
    end

    if jobcheck.client_id != client_id
      Job.update(jobcheck.id, client_id: client_id)
      #puts "Job Client changed"
    end

    return jobcheck.id

  end


  def currentjobs
    @module = 'current'
    build_request

    wfmresults=request
    wfmresultshash=Hash.from_xml(wfmresults)

    wfmresultshash['Response']['Jobs']['Job'].each do |job|
      clientid=clientvalidate(job['Client']['ID'], job['Client']['Name'])
      jobid=jobvalidate(job['ID'], job['Name'], job['State'], job['StartDate'], job['DueDate'], clientid)

    end
  end

  def jobcleanup
    jobs=Job.where.not(job_state: 'Completed').order('due_date asc')
    jobs.each do |job|

      @module = "get/#{job.job_no}"
      build_request

      wfmresult=request
      wfmresulthash=Hash.from_xml(wfmresult)

      clientid=clientvalidate(wfmresulthash['Response']['Job']['Client']['ID'], wfmresulthash['Response']['Job']['Client']['Name'])
      jobid=jobvalidate(wfmresulthash['Response']['Job']['ID'], wfmresulthash['Response']['Job']['Name'], wfmresulthash['Response']['Job']['State'], wfmresulthash['Response']['Job']['StartDate'], wfmresulthash['Response']['Job']['DueDate'], clientid)


    end
  end


end

app/controllers/base_slas_controller.rb
class BaseSlasController < SecuredController
  before_filter only: [:new, :edit, :create] do
    @period = Lookup.where(lookup_type: 'BusinessTime')
  end


  def index
    @baseslas = BaseSla.all
  end

  def show
    id = params[:id]
    @base_sla = BaseSla.find(id)
  end

  def new
    #@period = Lookup.where(lookup_type: 'BusinessTime')
    @base_sla = BaseSla.new
  end

  def create
    #@period = Lookup.where(lookup_type: 'BusinessTime')
    @base_sla = BaseSla.new(white_listed_params)
    if @base_sla.save
      flash[:success] = "New Base SLA #{@base_sla.name} saved successfully."
      redirect_to base_slas_path
    else
      render :new
    end
  end

  def edit
    @base_sla = BaseSla.find(params[:id])
  end

  def update
    @base_sla = BaseSla.find(params[:id])
    if @base_sla.update_attributes(white_listed_params)
      flash[:success] = "BaseSLA #{@base_sla.name} updated successfully."
      redirect_to base_slas_path
    else
      render :edit
    end
  end

  def destroy
    @base_sla = BaseSla.find_by_id(params[:id])
    @base_sla.delete if @base_sla
    flash[:success] = "BaseSLA #{@base_sla.name} deleted successfully."
    redirect_to base_slas_path
  end

 private

  def white_listed_params
    params.require(:base_sla).permit(:quantity, :period, :name)
  end



end

app/controllers/clients_controller.rb
class ClientsController < SecuredController

  def index
    @clients = Client.all.order('name asc')

  end

end

app/controllers/jobs_controller.rb
class JobsController < SecuredController

  def index
    @jobs = Job.where.not(job_state: 'Completed').order('due_date asc')
  end
end

app/controllers/secured_controller.rb
# Controllers which require full resource security should inherit from this
# class. The user also needs to be authenticated to access all controller actions.
class SecuredController < ApplicationController
  # This filter is invoked before the specified actions new, create, edit and update
  # The filter calls the function authenticate_user! in Devise. Devise by default
  # is configured to redirect the user to the sign_in url if the user does not have
  # a valid session cookie. If a valid session cookie exists the action is called
  # as per normal
  before_filter :authenticate_user! #, only: [:new, :create, :edit, :update]
end

app/controllers/users_controller.rb
class UsersController < SecuredController

def index
    @users = User.all
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @jobs = Job.where.not(job_state: 'Completed').order('due_date asc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_slas_helper.rb
module BaseSlasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/job_slas_helper.rb
module JobSlasHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/base_slas/_form.html.erb
<%= form_for @base_sla, html: { class: 'well form', role: 'form' } do |f| %>
  <%= render partial: 'shared/error_messages', object: @base_sla %>
  <div class="form-group">
    <%= f.label :name, 'Base SLA Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :quantity, 'Quantity per period' %>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :period %>
    <%= f.select(:period, @period.map { |g| [g.name, g.value]}) %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/base_slas/edit.html.erb
<%= render 'form' %>

app/views/base_slas/index.html.erb
<div class="container">
  <div class="row">
    <% if @baseslas.empty? %>
      <div class="col-md-12">
        <h1>
          There are no Base SLA's in the system at present.... did you forget to seed?
        </h1>
      </div>
    <% else %>
      <table class="table table-stripped">
        <thead>
          <tr>
            <td>Name</td>
            <td>Quantity</td>
            <td>Period</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
        <% @baseslas.each do |sla| %>
          <tr>
            <td>
              <%= sla.name %>
            </td>
            <td>
              <%= sla.quantity %>
            </td>
            <td>
              <%= sla.period %>
            </td>
            <td>
              <%= link_to 'Edit', edit_base_sla_path(sla) %> |
              <%= link_to 'Delete', base_sla_path(sla), method: :delete %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Add New BaseSLA", new_base_sla_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/base_slas/new.html.erb
<%= render 'form' %>

app/views/base_slas/show.html.erb
<h1><%= @base_sla.name %></h1>
<h2><%= @base_sla.quanity %></h2>
<h3><%= @base_sla.period %></h3>