config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :jobs
  resources :clients
  resources :base_slas
  resources :users, only: [:index, :show]

end

app/models/base_sla.rb
class BaseSla < ActiveRecord::Base
  validates_presence_of :quantity, :period, :name

  validates :period, inclusion: ['hours', 'days', 'hour', 'day']
  has_many :client_slas
end

app/models/business_unit.rb
class BusinessUnit < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base

validates_presence_of :name, :wfm_id


has_many :jobs
has_many :client_slas

end

app/models/client_sla.rb
class ClientSla < ActiveRecord::Base

 belongs_to :base_slas
end

app/models/job.rb
class Job < ActiveRecord::Base

  validates_presence_of :job_no, :job_type, :job_state, :start_date, :due_date, :client_id

  belongs_to :client
  has_many :job_slas
end

app/models/job_sla.rb
class JobSla < ActiveRecord::Base
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
   validates_presence_of :name, :value, :lookup_type
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates_presence_of :user_role
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         #:registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  validates_presence_of :first_name, :last_name, :email, :mobile, :role_id


  validates_format_of :email,
    :with  => Devise.email_regexp,
    :allow_blank => true,
    :if => :email_changed?


  belongs_to :role
end

app/models/wfm_call.rb
class WfmCall < ActiveRecord::Base
  after_initialize :default_values

  def default_values
    @api_user = ENV["WFM_API_USER"]
    @api_key = ENV["WFM_API_KEY"]
    @base_uri = 'https://api.workflowmax.com/job.api/'

  end

  def build_request
    #Need to Build the base get request
    @uri = "#{@base_uri}#{@module}?apiKey=#{@api_key}&accountKey=#{@api_user}"
  end

  def request
    rest_data = RestClient.get(@uri)
    return rest_data
  end

  def clientvalidate(id, name)
    clientcheck = Client.find_by_wfm_id(id)
    if clientcheck == nil
      Client.create(name: name, wfm_id: id)
      puts "Client Created #{name}"
      clientcheck = Client.find_by_wfm_id(id)
    end

    if clientcheck.name != name
      Client.update(clientcheck.id, name: name)
      puts "Client Name changed"
    end

    return clientcheck.id

  end

  def jobvalidate(id, job_type, job_state, start_date, due_date, client_id)
    jobcheck = Job.find_by_job_no(id)
    if jobcheck == nil
      Job.create(job_no: id, job_type: job_type, job_state: job_state, start_date: start_date, due_date: due_date, client_id: client_id)
      puts "Job Created #{job_type}"
      jobcheck = Job.find_by_job_no(id)
    end

    if jobcheck.job_type != job_type
      Job.update(jobcheck.id, job_type: job_type)
      puts "Job Name changed"
    end

    if jobcheck.job_state != job_state
      Job.update(jobcheck.id, job_state: job_state)
      puts "Job State changed"
    end

    if jobcheck.start_date != start_date
      Job.update(jobcheck.id, start_date: start_date)
      puts "Job Start changed"
    end

    if jobcheck.due_date != due_date
      Job.update(jobcheck.id, due_date: due_date)
      puts "Job Due changed"
    end

    if jobcheck.client_id != client_id
      Job.update(jobcheck.id, client_id: client_id)
      #puts "Job Client changed"
    end

    return jobcheck.id

  end


  def currentjobs
    @module = 'current'
    build_request

    wfmresults=request
    wfmresultshash=Hash.from_xml(wfmresults)

    wfmresultshash['Response']['Jobs']['Job'].each do |job|
      clientid=clientvalidate(job['Client']['ID'], job['Client']['Name'])
      jobid=jobvalidate(job['ID'], job['Name'], job['State'], job['StartDate'], job['DueDate'], clientid)

    end
  end

  def jobcleanup
    jobs=Job.where.not(job_state: 'Completed').order('due_date asc')
    jobs.each do |job|

      @module = "get/#{job.job_no}"
      build_request

      wfmresult=request
      wfmresulthash=Hash.from_xml(wfmresult)

      clientid=clientvalidate(wfmresulthash['Response']['Job']['Client']['ID'], wfmresulthash['Response']['Job']['Client']['Name'])
      jobid=jobvalidate(wfmresulthash['Response']['Job']['ID'], wfmresulthash['Response']['Job']['Name'], wfmresulthash['Response']['Job']['State'], wfmresulthash['Response']['Job']['StartDate'], wfmresulthash['Response']['Job']['DueDate'], clientid)


    end
  end


end

app/controllers/clients_controller.rb
class ClientsController < SecuredController

  def index
    @clients = Client.all.order('name asc')

  end

end

app/controllers/jobs_controller.rb
class JobsController < SecuredController

  def index
    @jobs = Job.where.not(job_state: 'Completed').order('due_date asc')
  end
end

app/controllers/users_controller.rb
class UsersController < SecuredController

def index
    @users = User.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_slas_helper.rb
module BaseSlasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/job_slas_helper.rb
module JobSlasHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
 <!-- <!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html> -->



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Job Tracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <!-- Start of header -->
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Job Tracker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Current Jobs', jobs_path %> </li>
            <li><%= link_to 'Clients', clients_path %> </li>
            <li><%= link_to 'Base SLA', base_slas_path %> </li>
            <li><%= link_to 'Users', users_path %> </li>
            <% if current_user %>
              <li>
                <%= link_to 'Sign Out', destroy_user_session_path, title: 'Sign Out', method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Sign In', new_user_session_path, title: 'Sign In', method: :new %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <!-- End of header -->

    <!-- Start of primary container -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>

          <%= yield %>
        </div>
      </div>
    </div>
    <!-- End of prmary container -->

    <!-- Start of footer -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <footer>
            <p>&copy; Interaction 2014</p>
          </footer>
        </div>
      </div>
    </div>
    <!-- End of footer -->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if error_messages.errors.any? %>
  <div class='alert-area'>
    <% error_messages.errors.full_messages.each do |msg| %>
      <%= content_tag(:div, raw("<button class='close' data-dismiss='alert'>
          ×
        </button> <i class='fa-fw fa fa-danger'></i> #{msg}"), class: "alert alert-danger fade in") %>
    <% end %>
  </div>
<% end %>